### ISSUE TITLE
aarch64 build?

### ISSUE THREAD

**Issue by poetaster** [ajalkane/ringingrestorer_sailfish#2] opened 2021-09-23 12:12 UTC
I can also help getting the app into chum (build.sailfishfishos.org) for automagical builds?

Thanks!

**Comment by ajalkane** [comment] 2021-09-24 10:56
Hey... I will try and find time to make an aarch64 build, hopefully with chum.

**Comment by poetaster** [comment] 2021-09-24 12:58
cool! thanks and let me know if you need any help with build/chum ... I'm maintaining a bunch of apps. otherwise piggz and rinigus are really responsive on #sailfishos (-porters) at OFTC irc.

**Comment by Orologiaio** [comment] 2022-08-22 07:48
I second this request, I just switched to an Xperia 10 iii and I'm constantly being reminded how useful this app is by not having it available whenever I put my phone in silent mode :)

I have no coding skills at all, but if I can help in any way, let me know.

**Comment by ajalkane** [comment] 2022-08-27 07:35
Hey guys... I said I tried to find time, but as it's already a year and I still haven't done it then I guess I must admit my failure. Any of you can do this? I'm ok with forking the codebase or whatever needs to be done.

**Comment by poetaster** [comment] 2022-08-28 09:48
> Hey guys... I said I tried to find time, but as it's already a year and I still haven't done it then I guess I must admit my failure. Any of you can do this? I'm ok with forking the codebase or whatever needs to be done.

I'll try to find some time next week. I'll fork first and let you know how it goes.

**Comment by poetaster** [comment] 2022-08-28 13:11
> I second this request, I just switched to an Xperia 10 iii and I'm constantly being reminded how useful this app is by not having it available whenever I put my phone in silent mode :)
> 
> I have no coding skills at all, but if I can help in any way, let me know.

I just made some minor changes to the spec and did an aarch64 build. You could try installing that:
https://github.com/poetaster/ringingrestorer_sailfish/releases/tag/1.5

I haven't had time to test it yet. Thanks!

**Comment by ajalkane** [comment] 2022-08-28 13:50
Thank you. I did a quick test that it seems to work 👍.

The application itself fails to detect the daemon is running though, so it gives an error message regarding that.

**Comment by Orologiaio** [comment] 2022-08-28 16:38
> Thank you. I did a quick test that it seems to work 👍.
> 
> The application itself fails to detect the daemon is running though, so it gives an error message regarding that.

I can confirm both things. App seemingly works but can't detect that the daemon is running. Thanks!

**Comment by poetaster** [comment] 2022-08-29 07:44
> Thank you. I did a quick test that it seems to work +1.
> 
> The application itself fails to detect the daemon is running though, so it gives an error message regarding that.

Could you post the error message? I'm guessing it has to do with dbus permissions?

**Comment by Orologiaio** [comment] 2022-08-29 16:08
> > Thank you. I did a quick test that it seems to work +1.
> > The application itself fails to detect the daemon is running though, so it gives an error message regarding that.
> 
> Could you post the error message? I'm guessing it has to do with dbus permissions?

This is what appears in the app itself if launched from the app drawer:

"RingingRestorer backend is not running. If you have just started your phone, close this application, wait a couple of minutes, and then try starting the application again."

If I launch it via terminal, instead, a couple of errors about missing libraries appear, but the app UI also starts and it properly shows the button saying "Stop RingingRestorer" and the message "RingingRestorer is active. When a profile changed from ringing to silent, will ask how long until ringing is resumed."

Here's a screenshot of the terminal output:

<img width="553" alt="RingingRestorer terminal launch" src="https://user-images.githubusercontent.com/6282482/187245040-a5565e0e-7f63-449c-8cb8-2211c1511197.png">

**Comment by Orologiaio** [comment] 2022-08-29 16:15
I also just took a look on my old Xperia X which also is on SFOS 4.4 like my Xperia 10 iii, and I can confirm what Cmdr-Zod is saying in the other thread: [https://github.com/ajalkane/ringingrestorer_sailfish/issues/3](url)

I probably never noticed this error message while I was still using the X before I switched to the 10 iii a couple weeks ago because RingingRestorer never stopped working, and I probably never launched the app itself recently (as you usually don't need to).

**Comment by Cmdr-Zod** [comment] 2022-08-29 16:46
I just tried your build on my Xperia 10 iii, I still see the error message in the UI regarding the backend not running, but so far it is working as expected. Thank you very much.
Please put it on Openrepos or Chum once it has received enough testing, I'm in the process of switching from an Xperia X to a 10 iii, and getting all the apps in 64bit is a small adventure on its own.

**Comment by poetaster** [comment] 2022-08-30 06:54
Ok, I've added a Sailjail disable block which might solve the issue with dbus calls to the service/systemd:
https://github.com/poetaster/ringingrestorer_sailfish/releases/tag/1.6 

Still having issues building on obs, but it's in the works.

**Comment by Orologiaio** [comment] 2022-08-30 15:54
> Ok, I've added a Sailjail disable block which might solve the issue with dbus calls to the service/systemd: https://github.com/poetaster/ringingrestorer_sailfish/releases/tag/1.6
> 
> Still having issues building on obs, but it's in the works.

It works!

**Comment by poetaster** [comment] 2022-08-30 20:10
> It works!
Great! I'll get it in rotation or maybe @ajalkane pushes the one build to openrepos. Here we go....

**Comment by poetaster** [comment] 2022-08-31 08:57
Ok, found the reason it won't compile on obs. From the pro: 

```
system(qdbusxml2cpp -p src/daemon/generated/mceiface/mceiface.h:src/daemon/generated/mceiface/mceiface.cpp src/daemon/nemo-keepalive/lib/mceiface.xml)
```
I don't think is actually being used in the build and so I've removed it. I also had to do some odd rpm install magic since the systemd unit didn't want to install as it would with Creator. 

If someone has the time, please test a build from:
https://build.merproject.org/project/show/home:poetaster:ringtonerestorer

If it works, I'll push it to chum.

**Comment by Orologiaio** [comment] 2022-08-31 12:35
> Ok, found the reason it won't compile on obs. From the pro:
> 
> ```
> system(qdbusxml2cpp -p src/daemon/generated/mceiface/mceiface.h:src/daemon/generated/mceiface/mceiface.cpp src/daemon/nemo-keepalive/lib/mceiface.xml)
> ```
> 
> I don't think is actually being used in the build and so I've removed it. I also had to do some odd rpm install magic since the systemd unit didn't want to install as it would with Creator.
> 
> If someone has the time, please test a build from: https://build.merproject.org/project/show/home:poetaster:ringtonerestorer
> 
> If it works, I'll push it to chum.

Works for me.

**Comment by ajalkane** [comment] 2022-08-31 14:57
> Ok, found the reason it won't compile on obs. From the pro:
> 
> ```
> system(qdbusxml2cpp -p src/daemon/generated/mceiface/mceiface.h:src/daemon/generated/mceiface/mceiface.cpp src/daemon/nemo-keepalive/lib/mceiface.xml)
> ```
> 
> I don't think is actually being used in the build and so I've removed it. I also had to do some odd rpm install magic since the systemd unit didn't want to install as it would with Creator.
> 
> If someone has the time, please test a build from: https://build.merproject.org/project/show/home:poetaster:ringtonerestorer
> 
> If it works, I'll push it to chum.

Thank you,

now there is no error message. But for some reason "Stop RingingRestorer" button does not have effect. It shows in UI that it's stopped, but still when putting phone to silent the restore dialog appears. On the other hand, the daemon notices this change because when setting the restore timeout in dialog, it has no effect.

How it should work is that if RingingRestorer is not active, then that timeout dialog does not appear. I'm not quite sure what's going on there. I tested with build 4.3.0.15_aarch64

If you have idea for a fix that's nice, but if not I can push this version already to OpenRepos.

**Comment by poetaster** [comment] 2022-08-31 15:05
> > Ok, found the reason it won't compile on obs. From the pro:
> > ```
> > system(qdbusxml2cpp -p src/daemon/generated/mceiface/mceiface.h:src/daemon/generated/mceiface/mceiface.cpp src/daemon/nemo-keepalive/lib/mceiface.xml)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I don't think is actually being used in the build and so I've removed it. I also had to do some odd rpm install magic since the systemd unit didn't want to install as it would with Creator.
> > If someone has the time, please test a build from: https://build.merproject.org/project/show/home:poetaster:ringtonerestorer
> > If it works, I'll push it to chum.
> 
> Thank you,
> 
> now there is no error message. But for some reason "Stop RingingRestorer" button does not have effect. It shows in UI that it's stopped, but still when putting phone to silent the restore dialog appears. On the other hand, the daemon notices this change because when setting the restore timeout in dialog, it has no effect.
> 
> How it should work is that if RingingRestorer is not active, then that timeout dialog does not appear. I'm not quite sure what's going on there. I tested with build 4.3.0.15_aarch64
> 
> If you have idea for a fix that's nice, but if not I can push this version already to OpenRepos.

Ok, perhaps the generated  interface is of significance. The error message was probably related to Sailjail. I just re-enabled that line and uploaded a rebuilt (QT creator build) file to: https://github.com/poetaster/ringingrestorer_sailfish/releases/tag/1.7

Another idea I had is that it could be, given how the unit files are being installed that it maybe there more than once?

**Comment by ajalkane** [comment] 2022-08-31 15:34
I went through the code, and maybe what I remembered was wrong because at quick glance I couldn't see the code that would prevent the dialog from opening.

Of course I can't for the life of me understand why it should open if RingingRestorer is not active, but that's not here nor there. I must have some reason :P. So to me it seems this build works correctly as the code is.

**Comment by poetaster** [comment] 2022-08-31 15:41
> I went through the code, and maybe what I remembered was wrong because at quick glance I couldn't see the code that would prevent the dialog from opening.
> 
> Of course I can't for the life of me understand why it should open if RingingRestorer is not active, but that's not here nor there. I must have some reason :P. So to me it seems this build works correctly as the code is.

Ok, if the app/service do what they are intended to, it's a moot point :) I think pushing the build from github is the better idea (I believe the obs builds might not even work on openrepos). If they work, I'll also post builds for x86 and armv7.

**Comment by ajalkane** [comment] 2022-08-31 15:49
Thanks! When there's builds usable on OpenRepos I can try uploading them there.

**Comment by Orologiaio** [comment] 2022-08-31 16:39
> > Ok, found the reason it won't compile on obs. From the pro:
> > ```
> > system(qdbusxml2cpp -p src/daemon/generated/mceiface/mceiface.h:src/daemon/generated/mceiface/mceiface.cpp src/daemon/nemo-keepalive/lib/mceiface.xml)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I don't think is actually being used in the build and so I've removed it. I also had to do some odd rpm install magic since the systemd unit didn't want to install as it would with Creator.
> > If someone has the time, please test a build from: https://build.merproject.org/project/show/home:poetaster:ringtonerestorer
> > If it works, I'll push it to chum.
> 
> Thank you,
> 
> now there is no error message. But for some reason "Stop RingingRestorer" button does not have effect. It shows in UI that it's stopped, but still when putting phone to silent the restore dialog appears. On the other hand, the daemon notices this change because when setting the restore timeout in dialog, it has no effect.
> 
> How it should work is that if RingingRestorer is not active, then that timeout dialog does not appear. I'm not quite sure what's going on there. I tested with build 4.3.0.15_aarch64
> 
> If you have idea for a fix that's nice, but if not I can push this version already to OpenRepos.

I confirm, the "stop daemon" button does nothing... sorry, when I tested the build I didn't think to also try disabling the app, only to check if it worked as intended when active :/

**Comment by poetaster** [comment] 2022-08-31 16:48
https://github.com/poetaster/ringingrestorer_sailfish/releases/tag/1.7 now has all the architectures.

The question about whether to publish depends on whether the stop daemon button is fundamental. We could make that a ticket if the functions are otherwise as they should be.

**Comment by Orologiaio** [comment] 2022-09-01 08:06
> https://github.com/poetaster/ringingrestorer_sailfish/releases/tag/1.7 now has all the architectures.
> 
> The question about whether to publish depends on whether the stop daemon button is fundamental. We could make that a ticket if the functions are otherwise as they should be.

I never use it, personally.

**Comment by poetaster** [comment] 2022-09-01 08:32
> Thanks! When there's builds usable on OpenRepos I can try uploading them there.
...
> I never use it, personally.

The files I uploaded under the release on github should be fine for openrepos....

**Comment by ajalkane** [comment] 2022-09-01 14:25
Thank you,

I've uploaded them to OpenRepos

**Closed as completed by ajalkane** 2022-09-01 14:25 UTC
